services:
  app:
    container_name: currencyhub
    build: .
    ports:
      - "8080:8080"
      - "9100:9100"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=currencyhub
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config:/app/configd
      - ./migrations:/app/migrations
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: currencyhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
